DROP SEQUENCE CLI_SEQ; 
CREATE SEQUENCE CLI_SEQ INCREMENT BY 1;

CREATE TABLE CLIENTES (
    ID_CLIENTE NUMBER(5) DEFAULT CLI_SEQ.NEXTVAL NOT NULL,
    NOME VARCHAR2(50),
    EMAIL VARCHAR2(50),
    TELEFONE VARCHAR2(50),
    CONSTRAINT CLI_PK PRIMARY KEY (ID_CLIENTE)
    )